# Generated by Django 5.0.3 on 2024-06-19 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=128)),
                ('fechaDeLanzamiento', models.DateField()),
                ('reproducciones', models.IntegerField(default=0)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Canciones', to='artista_api.artista')),
            ],
        ),
    ]
